export interface CountrySeed {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  /** Case-insensitive, whole-word aliases matched against story text (name, adjective, capital, common short forms). */
  aliases: string[];
  lat: number;
  lng: number;
}

/**
 * Reference table for keyword-based geotagging (see src/lib/geotag.ts) and for
 * placing map pins. Coordinates are each country's capital city, used as a
 * centroid — good enough for a country-level map view, not meant for precise
 * event geolocation.
 *
 * This list covers the countries most relevant to global geopolitics coverage.
 * To add a country: append an entry here, then run `npm run db:seed`.
 */
export const countries: CountrySeed[] = [
  {
    code: 'US',
    name: 'United States',
    aliases: ['united states', 'u.s.', 'usa', 'american', 'washington', 'white house', 'pentagon'],
    lat: 38.9072,
    lng: -77.0369,
  },
  {
    code: 'CA',
    name: 'Canada',
    aliases: ['canada', 'canadian', 'ottawa'],
    lat: 45.4215,
    lng: -75.6972,
  },
  {
    code: 'MX',
    name: 'Mexico',
    aliases: ['mexico', 'mexican', 'mexico city'],
    lat: 19.4326,
    lng: -99.1332,
  },
  {
    code: 'BR',
    name: 'Brazil',
    aliases: ['brazil', 'brazilian', 'brasilia'],
    lat: -15.7939,
    lng: -47.8828,
  },
  {
    code: 'AR',
    name: 'Argentina',
    aliases: ['argentina', 'argentine', 'buenos aires'],
    lat: -34.6037,
    lng: -58.3816,
  },
  {
    code: 'CL',
    name: 'Chile',
    aliases: ['chile', 'chilean', 'santiago'],
    lat: -33.4489,
    lng: -70.6693,
  },
  {
    code: 'CO',
    name: 'Colombia',
    aliases: ['colombia', 'colombian', 'bogota'],
    lat: 4.711,
    lng: -74.0721,
  },
  {
    code: 'VE',
    name: 'Venezuela',
    aliases: ['venezuela', 'venezuelan', 'caracas'],
    lat: 10.4806,
    lng: -66.9036,
  },
  { code: 'PE', name: 'Peru', aliases: ['peru', 'peruvian', 'lima'], lat: -12.0464, lng: -77.0428 },
  { code: 'CU', name: 'Cuba', aliases: ['cuba', 'cuban', 'havana'], lat: 23.1136, lng: -82.3666 },
  {
    code: 'GB',
    name: 'United Kingdom',
    aliases: [
      'united kingdom',
      'u.k.',
      'britain',
      'british',
      'england',
      'london',
      'downing street',
      'westminster',
    ],
    lat: 51.5072,
    lng: -0.1276,
  },
  {
    code: 'FR',
    name: 'France',
    aliases: ['france', 'french', 'paris', 'elysee'],
    lat: 48.8566,
    lng: 2.3522,
  },
  {
    code: 'DE',
    name: 'Germany',
    aliases: ['germany', 'german', 'berlin'],
    lat: 52.52,
    lng: 13.405,
  },
  { code: 'IT', name: 'Italy', aliases: ['italy', 'italian', 'rome'], lat: 41.9028, lng: 12.4964 },
  {
    code: 'ES',
    name: 'Spain',
    aliases: ['spain', 'spanish', 'madrid'],
    lat: 40.4168,
    lng: -3.7038,
  },
  {
    code: 'PT',
    name: 'Portugal',
    aliases: ['portugal', 'portuguese', 'lisbon'],
    lat: 38.7223,
    lng: -9.1393,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    aliases: ['netherlands', 'dutch', 'amsterdam', 'the hague'],
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    code: 'BE',
    name: 'Belgium',
    aliases: ['belgium', 'belgian', 'brussels'],
    lat: 50.8503,
    lng: 4.3517,
  },
  {
    code: 'PL',
    name: 'Poland',
    aliases: ['poland', 'polish', 'warsaw'],
    lat: 52.2297,
    lng: 21.0122,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    aliases: ['ukraine', 'ukrainian', 'kyiv', 'kiev'],
    lat: 50.4501,
    lng: 30.5234,
  },
  {
    code: 'RU',
    name: 'Russia',
    aliases: ['russia', 'russian', 'moscow', 'kremlin'],
    lat: 55.7558,
    lng: 37.6173,
  },
  {
    code: 'BY',
    name: 'Belarus',
    aliases: ['belarus', 'belarusian', 'minsk'],
    lat: 53.9006,
    lng: 27.559,
  },
  {
    code: 'RO',
    name: 'Romania',
    aliases: ['romania', 'romanian', 'bucharest'],
    lat: 44.4268,
    lng: 26.1025,
  },
  {
    code: 'GR',
    name: 'Greece',
    aliases: ['greece', 'greek', 'athens'],
    lat: 37.9838,
    lng: 23.7275,
  },
  {
    code: 'TR',
    name: 'Turkey',
    aliases: ['turkey', 'turkish', 'ankara', 'turkiye'],
    lat: 39.9334,
    lng: 32.8597,
  },
  {
    code: 'SE',
    name: 'Sweden',
    aliases: ['sweden', 'swedish', 'stockholm'],
    lat: 59.3293,
    lng: 18.0686,
  },
  {
    code: 'FI',
    name: 'Finland',
    aliases: ['finland', 'finnish', 'helsinki'],
    lat: 60.1699,
    lng: 24.9384,
  },
  {
    code: 'NO',
    name: 'Norway',
    aliases: ['norway', 'norwegian', 'oslo'],
    lat: 59.9139,
    lng: 10.7522,
  },
  {
    code: 'DK',
    name: 'Denmark',
    aliases: ['denmark', 'danish', 'copenhagen'],
    lat: 55.6761,
    lng: 12.5683,
  },
  {
    code: 'IE',
    name: 'Ireland',
    aliases: ['ireland', 'irish', 'dublin'],
    lat: 53.3498,
    lng: -6.2603,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    aliases: ['switzerland', 'swiss', 'geneva', 'bern'],
    lat: 46.948,
    lng: 7.4474,
  },
  {
    code: 'AT',
    name: 'Austria',
    aliases: ['austria', 'austrian', 'vienna'],
    lat: 48.2082,
    lng: 16.3738,
  },
  {
    code: 'HU',
    name: 'Hungary',
    aliases: ['hungary', 'hungarian', 'budapest'],
    lat: 47.4979,
    lng: 19.0402,
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    aliases: ['czech republic', 'czechia', 'czech', 'prague'],
    lat: 50.0755,
    lng: 14.4378,
  },
  {
    code: 'CN',
    name: 'China',
    aliases: ['china', 'chinese', 'beijing'],
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    aliases: ['taiwan', 'taiwanese', 'taipei'],
    lat: 25.033,
    lng: 121.5654,
  },
  {
    code: 'JP',
    name: 'Japan',
    aliases: ['japan', 'japanese', 'tokyo'],
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    code: 'KR',
    name: 'South Korea',
    aliases: ['south korea', 'south korean', 'seoul', 'republic of korea'],
    lat: 37.5665,
    lng: 126.978,
  },
  {
    code: 'KP',
    name: 'North Korea',
    aliases: ['north korea', 'north korean', 'pyongyang', "democratic people's republic of korea"],
    lat: 39.0392,
    lng: 125.7625,
  },
  {
    code: 'IN',
    name: 'India',
    aliases: ['india', 'indian', 'new delhi'],
    lat: 28.6139,
    lng: 77.209,
  },
  {
    code: 'PK',
    name: 'Pakistan',
    aliases: ['pakistan', 'pakistani', 'islamabad'],
    lat: 33.6844,
    lng: 73.0479,
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    aliases: ['bangladesh', 'bangladeshi', 'dhaka'],
    lat: 23.8103,
    lng: 90.4125,
  },
  {
    code: 'AF',
    name: 'Afghanistan',
    aliases: ['afghanistan', 'afghan', 'kabul'],
    lat: 34.5553,
    lng: 69.2075,
  },
  {
    code: 'MM',
    name: 'Myanmar',
    aliases: ['myanmar', 'burma', 'burmese', 'naypyidaw'],
    lat: 19.7633,
    lng: 96.0785,
  },
  {
    code: 'TH',
    name: 'Thailand',
    aliases: ['thailand', 'thai', 'bangkok'],
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    aliases: ['vietnam', 'vietnamese', 'hanoi'],
    lat: 21.0278,
    lng: 105.8342,
  },
  {
    code: 'PH',
    name: 'Philippines',
    aliases: ['philippines', 'filipino', 'manila'],
    lat: 14.5995,
    lng: 120.9842,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    aliases: ['indonesia', 'indonesian', 'jakarta'],
    lat: -6.2088,
    lng: 106.8456,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    aliases: ['malaysia', 'malaysian', 'kuala lumpur'],
    lat: 3.139,
    lng: 101.6869,
  },
  {
    code: 'SG',
    name: 'Singapore',
    aliases: ['singapore', 'singaporean'],
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    code: 'AU',
    name: 'Australia',
    aliases: ['australia', 'australian', 'canberra'],
    lat: -35.2809,
    lng: 149.13,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    aliases: ['new zealand', 'wellington'],
    lat: -41.2865,
    lng: 174.7762,
  },
  {
    code: 'IL',
    name: 'Israel',
    aliases: ['israel', 'israeli', 'jerusalem', 'tel aviv'],
    lat: 31.7683,
    lng: 35.2137,
  },
  {
    code: 'PS',
    name: 'Palestine',
    aliases: ['palestine', 'palestinian', 'gaza', 'west bank', 'ramallah'],
    lat: 31.9522,
    lng: 35.2332,
  },
  {
    code: 'LB',
    name: 'Lebanon',
    aliases: ['lebanon', 'lebanese', 'beirut'],
    lat: 33.8938,
    lng: 35.5018,
  },
  {
    code: 'SY',
    name: 'Syria',
    aliases: ['syria', 'syrian', 'damascus'],
    lat: 33.5138,
    lng: 36.2765,
  },
  { code: 'IQ', name: 'Iraq', aliases: ['iraq', 'iraqi', 'baghdad'], lat: 33.3152, lng: 44.3661 },
  { code: 'IR', name: 'Iran', aliases: ['iran', 'iranian', 'tehran'], lat: 35.6892, lng: 51.389 },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    aliases: ['saudi arabia', 'saudi', 'riyadh'],
    lat: 24.7136,
    lng: 46.6753,
  },
  { code: 'YE', name: 'Yemen', aliases: ['yemen', 'yemeni', 'sanaa'], lat: 15.3694, lng: 44.191 },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    aliases: ['united arab emirates', 'uae', 'emirati', 'abu dhabi', 'dubai'],
    lat: 24.4539,
    lng: 54.3773,
  },
  { code: 'QA', name: 'Qatar', aliases: ['qatar', 'qatari', 'doha'], lat: 25.2854, lng: 51.531 },
  {
    code: 'JO',
    name: 'Jordan',
    aliases: ['jordan', 'jordanian', 'amman'],
    lat: 31.9454,
    lng: 35.9284,
  },
  {
    code: 'EG',
    name: 'Egypt',
    aliases: ['egypt', 'egyptian', 'cairo'],
    lat: 30.0444,
    lng: 31.2357,
  },
  {
    code: 'LY',
    name: 'Libya',
    aliases: ['libya', 'libyan', 'tripoli'],
    lat: 32.8872,
    lng: 13.1913,
  },
  {
    code: 'KW',
    name: 'Kuwait',
    aliases: ['kuwait', 'kuwaiti', 'kuwait city'],
    lat: 29.3759,
    lng: 47.9774,
  },
  {
    code: 'GE',
    name: 'Georgia',
    aliases: ['georgian', 'tbilisi', 'abkhazia', 'south ossetia'],
    lat: 41.7151,
    lng: 44.8271,
  },
  {
    code: 'AM',
    name: 'Armenia',
    aliases: ['armenia', 'armenian', 'yerevan'],
    lat: 40.1792,
    lng: 44.4991,
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    aliases: ['azerbaijan', 'azerbaijani', 'baku'],
    lat: 40.4093,
    lng: 49.8671,
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    aliases: ['kazakhstan', 'kazakh', 'astana'],
    lat: 51.1694,
    lng: 71.4491,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    aliases: ['south africa', 'south african', 'pretoria', 'johannesburg'],
    lat: -25.7461,
    lng: 28.1881,
  },
  {
    code: 'NG',
    name: 'Nigeria',
    aliases: ['nigeria', 'nigerian', 'abuja', 'lagos'],
    lat: 9.0765,
    lng: 7.3986,
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    aliases: ['ethiopia', 'ethiopian', 'addis ababa'],
    lat: 9.03,
    lng: 38.74,
  },
  {
    code: 'KE',
    name: 'Kenya',
    aliases: ['kenya', 'kenyan', 'nairobi'],
    lat: -1.2921,
    lng: 36.8219,
  },
  {
    code: 'SD',
    name: 'Sudan',
    aliases: ['sudan', 'sudanese', 'khartoum'],
    lat: 15.5007,
    lng: 32.5599,
  },
  {
    code: 'SO',
    name: 'Somalia',
    aliases: ['somalia', 'somali', 'mogadishu'],
    lat: 2.0469,
    lng: 45.3182,
  },
  { code: 'ML', name: 'Mali', aliases: ['mali', 'malian', 'bamako'], lat: 12.6392, lng: -8.0029 },
  {
    code: 'CD',
    name: 'DR Congo',
    aliases: ['democratic republic of congo', 'dr congo', 'congolese', 'kinshasa'],
    lat: -4.4419,
    lng: 15.2663,
  },
  { code: 'GH', name: 'Ghana', aliases: ['ghana', 'ghanaian', 'accra'], lat: 5.6037, lng: -0.187 },
];
